### ISSUE TITLE
Creation of the betterdoors folder

### ISSUE THREAD

**Issue by thecrankytech** [mozi-h/Better-Doors#1]
Could I recommend you create the data/betterdoors folder when the addon starts up or define in the readme that it needs to be created before group data can be saved?

I had a hell of time-saving group data until I created the betterdoors folder. I had no idea it doesn't do it automatically and I didn't see any mention that It needs to be manually created.

**Comment by mozi-h** [comment]
Just tested it. You're right, the directory won't get created automatically, only files within such and as better doors never checks if writing is successful and keeps an in-memory copy, it all seems fine until you restart the server. This slipped through my own testing.

Thanks for finding this (and actually using GitHub to save my sanity)! I'll fix this very soon and add a minor convenience server concmd on top.

**Comment by thecrankytech** [comment]
No worries mate, awesome addon.
